[libdefaults]
  default_realm = BANK.LOCAL
  dns_lookup_kdc = false
  dns_lookup_realm = false

[realms]
  BANK.LOCAL = {
    kdc = kdc.bank.local:88
    admin_server = kdc.bank.local
  }

[domain_realm]
  .bank.local = BANK.LOCAL
  bank.local = BANK.LOCAL
